spring:
  datasource:
    url: jdbc:mysql://listtoken-mysql-tokyo.cabzwlv33h9m.ap-northeast-1.rds.amazonaws.com/listtoken?useSSL=true
    username: root
    password: listtoken
    driver-class-name: com.mysql.jdbc.Driver
user.auth.openFlag: true